# Generated by Django 6.0.6 on 2026-07-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
